use_frameworks!

target 'CodableMapper_Example' do
  pod 'CodableMapper', :path => '../'

  target 'CodableMapper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
